---
- name: My Playbook
  host: all
  become: yes

  vars: 
    mytext: "hello"

  tasks:
  - name: Ping test
    ping:
  
  - name: Unregister Server from Load Balancer
    shell: echo this server {{inventory_hostname}} was deregistred fom our Load Balancer,node name is {{ansible_nodename}} >> /home/log.txt
    delegate_to: 127.0.0.1 

  - name: Create File
    copy:
      dest: /home/file1.txt
      content: |
        This is FileN1
        On English Hello World
        On Russian {{mytext}}
    delegate_to: linux3

  
  - name: Create fiel 2
    copy:
      dest: /home/file2.txt
      content: |
        This is FileN2
        On English Hello World
        On Russian {{mytext}}

  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0
        
  - name: Wait server to come up
    wait_for:
        host: "{{inventory_hostname}}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1