- name: Loops Playbook
  hosts: all
  become: yes

  tasks:
  - name: Say Hello to all
    debug: msg="Hello  {{ item }}"
    loop:    #or with_items
        - "Item 1"
        - "Item 2"
        - "Item 3"

  - name: Loop Until example
    shell: echo -n  S >> myfile.txt && cat myfile.txt 
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("SSSS") == false

  - name: Print Final output
    debug: 
      var: output.stdout

  - name: Install many packaged
    yum: name={{item}} state= installed
    with_items:
          - python
          - mysql-client
          - tree
